title: Co-Learning
description: Course on Large Language Models
theme: just-the-docs

# enable search
search_enabled: true

collections:
  staffers:
    output: false

sass:
  custom_dir: _sass/custom

# 设置主页默认布局
defaults:
  - scope:
      path: ""
    values:
      layout: default
