title: Spoon CoLearning
description: Course on Large Language Models
remote_theme: just-the-docs/just-the-docs

# 设置部署路径（改为你当前的仓库名）
baseurl: "/spoon-colearning"

# 启用相对路径和边栏
just_the_docs:
  relative_links: true
  show_sidebar: true

# 启用搜索功能
search_enabled: true

# 集合：用于讲师页等
collections:
  staffers:
    output: true

# 自定义样式路径（如未使用可省略）
sass:
  custom_dir: _sass/custom

# 默认布局
defaults:
  - scope:
      path: ""
    values:
      layout: default
